services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - ./order-service/ecs/local/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: order_ms_adm
    volumes:
      - ./postgres-data:/tmp/postgres/data
      # - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
